### ISSUE TITLE
ゲーム中にソケットを閉じた際のハンドリング

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#194]
現状、ハンドリングしてないのでsendしようとして例外吐きますね
```
pong-server   | Exception inside application: Attempt to send on a closed protocol
pong-server   | Traceback (most recent call last):
pong-server   |   File "/usr/local/lib/python3.12/site-packages/django/contrib/staticfiles/handlers.py", line 101, in __call__
pong-server   |     return await self.application(scope, receive, send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/routing.py", line 62, in __call__
pong-server   |     return await application(scope, receive, send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/security/websocket.py", line 37, in __call__
pong-server   |     return await self.application(scope, receive, send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/sessions.py", line 47, in __call__
pong-server   |     return await self.inner(dict(scope, cookies=cookies), receive, send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/sessions.py", line 263, in __call__
pong-server   |     return await self.inner(wrapper.scope, receive, wrapper.send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/auth.py", line 185, in __call__
pong-server   |     return await super().__call__(scope, receive, send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/middleware.py", line 24, in __call__
pong-server   |     return await self.inner(scope, receive, send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/routing.py", line 132, in __call__
pong-server   |     return await application(
pong-server   |            ^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/consumer.py", line 94, in app
pong-server   |     return await consumer(scope, receive, send)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/consumer.py", line 58, in __call__
pong-server   |     await await_many_dispatch(
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/utils.py", line 50, in await_many_dispatch
pong-server   |     await dispatch(result)
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/consumer.py", line 73, in dispatch
pong-server   |     await handler(message)
pong-server   |   File "/app/pong/consumers.py", line 226, in ball_message
pong-server   |     await self.send_game_data(game_status=True, message=message, timestamp=timestamp, sound_type=sound_type)
pong-server   |   File "/app/pong/consumers.py", line 229, in send_game_data
pong-server   |     await self.send(text_data=json.dumps({
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/generic/websocket.py", line 218, in send
pong-server   |     await super().send({"type": "websocket.send", "text": text_data})
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/consumer.py", line 81, in send
pong-server   |     await self.base_send(message)
pong-server   |   File "/usr/local/lib/python3.12/site-packages/channels/sessions.py", line 226, in send
pong-server   |     return await self.real_send(message)
pong-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pong-server   |   File "/usr/local/lib/python3.12/site-packages/daphne/server.py", line 241, in handle_reply
pong-server   |     protocol.handle_reply(message)
pong-server   |   File "/usr/local/lib/python3.12/site-packages/daphne/ws_protocol.py", line 207, in handle_reply
pong-server   |     self.serverSend(message["text"], False)
pong-server   |   File "/usr/local/lib/python3.12/site-packages/daphne/ws_protocol.py", line 261, in serverSend
pong-server   |     self.sendMessage(content.encode("utf8"), binary)
pong-server   |   File "/usr/local/lib/python3.12/site-packages/autobahn/websocket/protocol.py", line 2275, in sendMessage
pong-server   |     raise Disconnected("Attempt to send on a closed protocol")
pong-server   | autobahn.exception.Disconnected: Attempt to send on a closed protocol
```

**Comment by monksoffunk** [comment]
pong-serverとpong4-serverに例外処理を
