### ISSUE TITLE
ゲーム終了前に新たなマッチを開始してしまう

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#218]
#208 で触れた問題

pong-serverからのゲームオーバーの通知に先行して次のマッチのトークンが通知された場合、クライアントはゲーム終了の処理を行わないまま新たなゲームを開始してしまう。
その後すぐに前マッチのGame Overの通知が届くと前マッチのソケットは閉じられるが、その際にcontainetIdがクリアされるためか新マッチの画面は描画されず、操作もできない（詳細は未確認）。

対処方法はいくつかありそう
- クライアント側でゲーム状態を持たせて（たとえば終了するまでcontainetIdを保持）、終了していなかったら強制的に前のマッチを切断・終了処理する
- backend側でPlayerの状態をチェックして受入可能になってからトークンを送る（サーバーの処理を重くしたくないのであまりやりたくはない）
- ゲーム終了時に結果画面を出すことでゲームが重ならないようにする（これが可能なら一番良さそう）

============
              4人エントリーし、adminで時間を数分前にセットすれば開始時刻にトーナメントがスタートします。
しかしラウンド1（1試合目）が終わってラウンド2へと移行する際に不具合が起こります（頻度は半々程度）。

下記ログは異常系です。ラウンド1はpong/118で正常に動いていましたが、試合が終わってGame Overの処理がされる前に次のラウンドのjwtが届いてしまって新たにpong/120を開いてしまっています。結果としてクライアントにゲーム画面が表示されません（が水面下でゲームは進みます。しかしゲーム進行もなにかおかしく、得点が11点になったりする）。

@Chanmachan 
どの部分でハンドルすべきか難しいです。 現象確認お願いします 🙏

```
URL = pong/120
websocket.js:34 WebSocket for pong/120 is open now.
WebsocketHandler.js:92 WebSocket for pong/120 is open!!!
websocket.js:102 Message sent to pong/120: {action: 'authenticate', jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lX25hb…mQifQ.pVvw-_3XfenybMHlv6WGrvTIH6RzsulKanbaptj0ucU', player_name: 'player2'}
WebsocketHandler.js:99 Token sent to pong-server
GamePlay.js:202 RIGHT_PADDLE:  10   LEFT_PADDLE:  5
GamePlay.js:174 Game Over
websocket.js:94 WebSocket for pong/118 has been closed.
router.js:107 router in
```

_Originally posted by @monksoffunk in https://github.com/scandamus/ft_transcendence/issues/208#issuecomment-2227377277_

**Comment by Chanmachan** [comment]
現在のブランチの最新コミットでみているのですが、celeryコンテナでエラーが起きてて起動できずにいるので現状手元で試せていません。が、サーバーからgameoverが送られてきたら #212 の話と被ってきますが、「数秒後ページ移動」するように変更してみるとかですかね？
> ゲーム終了時に結果画面を出す
それでうまくいくようでしたらその数秒間だけ画面切り替わるようにする形で

**Comment by Chanmachan** [comment]
次のマッチのトークンが送られるタイミングを確認します

**Comment by monksoffunk** [comment]
#208 じゃないとこの問題は起きないです

**Comment by Chanmachan** [comment]
> > #208 じゃないとこの問題は起きないです
> 
> #208 の最新コミットです！



> > #208 じゃないとこの問題は起きないです
> 
> ~#208 の最新コミットです！~ そういう話ではないですなこれ

トーナメントのコードもう少し確認します

**Comment by monksoffunk** [comment]
最新コミットでのエラーログをいただけると助かります🙏

**Comment by Chanmachan** [comment]
```
backend       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0005_alter_player_lang, 0005_merge_20240710_0904 in players).
backend       | To fix them run 'python manage.py makemigrations --merge'
backend       | Using selector: EpollSelector
db            | 2024-07-15 14:43:44.029 UTC [83] ERROR:  relation "auth_user" does not exist at character 22
db            | 2024-07-15 14:43:44.029 UTC [83] STATEMENT:  SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_superuser" AND "auth_user"."username" = 'usersuper') LIMIT 1
backend       | Traceback (most recent call last):
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
backend       |     return self.cursor.execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
backend       | LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_supe...
backend       |                              ^
backend       | 
backend       | 
backend       | The above exception was the direct cause of the following exception:
backend       | 
backend       | Traceback (most recent call last):
backend       |   File "/app/manage.py", line 22, in <module>
backend       |     main()
backend       |   File "/app/manage.py", line 18, in main
backend       |     execute_from_command_line(sys.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
backend       |     utility.execute()
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
backend       |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
backend       |     self.execute(*args, **cmd_options)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
backend       |     output = self.handle(*args, **options)
backend       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/shell.py", line 127, in handle
backend       |     exec(sys.stdin.read(), globals())
backend       |   File "<string>", line 4, in <module>
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1241, in exists
backend       |     return self.query.has_results(using=self.db)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 566, in has_results
backend       |     return compiler.has_results()
backend       |            ^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1528, in has_results
backend       |     return bool(self.execute_sql(SINGLE))
backend       |                 ^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
backend       |     cursor.execute(sql, params)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
backend       |     return super().execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
backend       |     return self._execute_with_wrappers(
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
backend       |     return executor(sql, params, many, context)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
backend       |     with self.db.wrap_database_errors:
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
backend       |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
backend       |     return self.cursor.execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | django.db.utils.ProgrammingError: relation "auth_user" does not exist
backend       | LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_supe...
backend       |                              ^
backend       | 
backend       | Using selector: EpollSelector
backend       | Traceback (most recent call last):
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
db            | 2024-07-15 14:43:44.712 UTC [84] ERROR:  relation "auth_user" does not exist at character 22
backend       |     return self.cursor.execute(sql, params)
db            | 2024-07-15 14:43:44.712 UTC [84] STATEMENT:  SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_superuser" AND "auth_user"."username" = 'usersuper') LIMIT 1
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
backend       | LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_supe...
backend       |                              ^
backend       | 
backend       | 
backend       | The above exception was the direct cause of the following exception:
backend       | 
backend       | Traceback (most recent call last):
backend       |   File "/app/manage.py", line 22, in <module>
backend       |     main()
backend       |   File "/app/manage.py", line 18, in main
backend       |     execute_from_command_line(sys.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
backend       |     utility.execute()
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
backend       |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
backend       |     self.execute(*args, **cmd_options)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
backend       |     output = self.handle(*args, **options)
backend       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/shell.py", line 127, in handle
backend       |     exec(sys.stdin.read(), globals())
backend       |   File "<string>", line 5, in <module>
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1241, in exists
backend       |     return self.query.has_results(using=self.db)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 566, in has_results
backend       |     return compiler.has_results()
backend       |            ^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1528, in has_results
backend       |     return bool(self.execute_sql(SINGLE))
backend       |                 ^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
backend       |     cursor.execute(sql, params)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
backend       |     return super().execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
backend       |     return self._execute_with_wrappers(
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
backend       |     return executor(sql, params, many, context)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
backend       |     with self.db.wrap_database_errors:
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
backend       |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
backend       |     return self.cursor.execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | django.db.utils.ProgrammingError: relation "auth_user" does not exist
backend       | LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_supe...
backend       |                              ^
backend       | 
backend       | Using selector: EpollSelector
backend       | Traceback (most recent call last):
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
db            | 2024-07-15 14:43:45.291 UTC [85] ERROR:  relation "auth_user" does not exist at character 280
backend       |     return self.cursor.execute(sql, params)
db            | 2024-07-15 14:43:45.291 UTC [85] STATEMENT:  SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."username" = 'testplayer0' LIMIT 21
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
backend       | LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
backend       |                                                              ^
backend       | 
backend       | 
backend       | The above exception was the direct cause of the following exception:
backend       | 
backend       | Traceback (most recent call last):
backend       |   File "/app/manage.py", line 22, in <module>
backend       |     main()
backend       |   File "/app/manage.py", line 18, in main
backend       |     execute_from_command_line(sys.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
backend       |     utility.execute()
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
backend       |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
backend       |     self.execute(*args, **cmd_options)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
backend       |     output = self.handle(*args, **options)
backend       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/shell.py", line 127, in handle
backend       |     exec(sys.stdin.read(), globals())
backend       |   File "<string>", line 8, in <module>
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
backend       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
backend       |     num = len(clone)
backend       |           ^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 380, in __len__
backend       |     self._fetch_all()
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1881, in _fetch_all
backend       |     self._result_cache = list(self._iterable_class(self))
backend       |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
backend       |     results = compiler.execute_sql(
backend       |               ^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
backend       |     cursor.execute(sql, params)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
backend       |     return super().execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
backend       |     return self._execute_with_wrappers(
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
backend       |     return executor(sql, params, many, context)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
backend       |     with self.db.wrap_database_errors:
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
backend       |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
backend       |     return self.cursor.execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | django.db.utils.ProgrammingError: relation "auth_user" does not exist
backend       | LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
backend       |                                                              ^
backend       | 
backend       | Using selector: EpollSelector
backend       | Using selector: EpollSelector
backend       | Watching for file changes with StatReloader
backend       | Waiting for apps ready_event.
backend       | Apps ready_event triggered. Sending autoreload_started signal.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/django_celery_beat/templates with glob **/*.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/rest_framework/templates with glob **/*.
backend       | Watching dir /app/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/daphne/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/corsheaders/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/rest_framework/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/token_blacklist/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/channels/locale with glob **/*.mo.
backend       | Watching dir /app/players/locale with glob **/*.mo.
backend       | Watching dir /app/game/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/django_celery_beat/locale with glob **/*.mo.
backend       | Watching dir /usr/local/lib/python3.12/site-packages/django_celery_results/locale with glob **/*.mo.
backend       | File /usr/local/lib/python3.12/site-packages/twisted/_threads/_threadworker.py first seen with mtime 1721047215.985186
backend       | File /usr/local/lib/python3.12/site-packages/twisted/internet/process.py first seen with mtime 1721047216.001186
backend       | File /usr/local/lib/python3.12/site-packages/rest_framework/utils/formatting.py first seen with mtime 1721047217.548186
backend       | File /usr/local/lib/python3.12/site-packages/twisted/python/compat.py first seen with mtime 1721047216.028186
backend       | File /usr/local/lib/python3.12/site-packages/rest_framework/negotiation.py first seen with mtime 1721047217.527186
backend       | File /usr/local/lib/python3.12/asyncio/staggered.py first seen with mtime 1719953356.0
backend       | File /usr/local/lib/python3.12/email/base64mime.py first seen with mtime 1719953356.0
backend       | File /usr/local/lib/python3.12/site-packages/django/contrib/auth/__init__.py first seen with mtime 1721047214.808186
backend       | File /usr/local/lib/python3.12/lib-dynload/_uuid.cpython-312-aarch64-linux-gnu.so first seen with mtime 1719953362.0
backend       | File /usr/local/lib/python3.12/site-packages/django/utils/version.py first seen with mtime 1721047214.989186
backend       | File /usr/local/lib/python3.12/site-packages/django/views/decorators/__init__.py first seen with mtime 1721047214.990186
backend       | File /usr/local/lib/python3.12/asyncio/format_helpers.py first seen with mtime 1719953356.0
backend       | File /usr/local/lib/python3.12/email/charset.py first seen with mtime 1719953356.0
backend       | File /usr/local/lib/python3.12/site-packages/jwt/utils.py first seen with mtime 1721047213.742186
backend       | File /usr/local/lib/python3.12/site-packages/django/db/utils.py first seen with mtime 1721047214.966186
backend       | File /usr/local/lib/python3.12/site-packages/celery/app/annotations.py first seen with mtime 1721047218.138186
backend       | File /usr/local/lib/python3.12/site-packages/django/contrib/staticfiles/checks.py first seen with mtime 1721047214.958186
backend       | File /usr/local/lib/python3.12/site-packages/timezone_field/choices.py first seen with mtime 1721047217.620186
backend       | File /usr/local/lib/python3.12/site-packages/django/utils/_os.py first seen with mtime 1721047214.986186
backend       | File /usr/local/lib/python3.12/site-packages/rest_framework_simplejwt/serializers.py first seen with mtime 1721047218.112186
backend       | File /usr/local/lib/python3.12/site-packages/twisted/python/filepath.py first seen with mtime 1721047216.029186
backend       | File /usr/local/lib/python3.12/asyncio/exceptions.py first seen with mtime 1719953356.0
backend       | File /usr/local/lib/python3.12/site-packages/django/contrib/postgres/fields/citext.py first seen with mtime 1721047214.904186
backend       | File /usr/local/lib/python3.12/site-packages/twisted/logger/_flatten.py first seen with mtime 1721047216.009186
backend       | File /usr/local/lib/python3.12/site-packages/django/db/models/functions/comparison.py first seen with mtime 1721047214.975186
backend       | File /usr/local/lib/python3.12/site-packages/autobahn/wamp/websocket.py first seen with mtime 1721047218.328186
backend       | File /usr/local/lib/python3.12/site-packages/rest_framework/exceptions.py first seen with mtime 1721047217.526186
backend       | File /usr/local/lib/python3.12/site-packages/rest_framework/utils/encoders.py first seen with mtime 1721047217.548186
backend       | File /usr/local/lib/python3.12/site-packages/celery/app/registry.py first seen with mtime 1721047218.139186
backend       | File /usr/local/lib/python3.12/asyncio/base_events.py first seen with mtime 1719953356.0
backend       | File /usr/local/lib/python3.12/site-packages/celery/utils/nodenames.py first seen with mtime 1721047218.147186
backend       | File /usr/local/lib/python3.12/site-packages/django/core/checks/messages.py first seen with mtime 1721047214.960186
backend       | File /usr/local/lib/python3.12/unittest/main.py first seen with mtime 1719953357.0
backend       | File /usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/operations.py first seen with mtime 1721047214.969186
backend       | File /usr/local/lib/python3.12/site-packages/attr/_make.py first seen with mtime 1721047214.408186
backend       | File /usr/local/lib/python3.12/site-packages/django/db/migrations/migration.py first seen with mtime 1721047214.970186
backend       | File /usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/creation.py first seen with mtime 1721047214.969186
backend       | File /usr/local/lib/python3.12/zipfile/_path/__init__.py first seen with mtime 1719953357.0
backend       | File /usr/local/lib/python3.12/site-packages/kombu/entity.py first seen with mtime 1721047217.436186
backend       | File /usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/base
```

こんな感じです。さっきはceleryだったのですが、backendでのエラーになってました。
機密情報のenvではWARNがでたので、以下のように変更してビルドしました。
```env
SCANDAMUS_PATH=./django/scandamus
SCANDAMUS_STATIC_SRCS_PATH=./frontend/static_srcs
DEBUG=True
DOMAIN_NAME=localhost

# SECRET KEYS
FRONTEND_SECRET_KEY=development-secret-key-dont-use-when-deploy
BACKEND_SECRET_KEY=development-secret-key2-dont-use-when-deploy
BACKEND_CHANNEL_SECRET_KEY=development-secret-key3-dont-use-when-deploy
PONG_SERVER_SECRET_KEY=development-secret-key4-dont-use-when-deploy
PONG_SERVER_CHANNEL_SECRET_KEY=development-secret-key5-dont-use-when-deploy

# SIGNING KEYS
BACKEND_JWT_SIGNING_KEY=development-signing-key-dont-use-when-deploy
GAME_JWT_SIGNING_KEY=development-signing-key2-dont-use-when-deploy
PONG_SERVER_SIGNING_KEY=development-signing-key-dont-use-when-deploy

# SSL CERTIFICATE SETUP
CERTS=~/.certs
COUNTRY=JP
STATE=Tokyo
LOCALITY=Shinjuku-ku
ORGANIZATION=42 network
ORGANIZATION_UNIT=42 tokyo
EMAIL=admin@${DOMAIN_NAME}

# DATABASE SETUP
DB_NAME=scandamus_db
DB_USER=nop42
DB_PASSWORD=user42

# DJANGO_SUPER_USER
DJANGO_SU_USER=usersuper
DJANGO_SU_MAIL=aaa@aaaaamail.com
DJANGO_SU_PASSWORD=TLC3XkL@R

# DJANGO_PLAYER1
DJANGO_PLAYER1_USER=playertest1
DJANGO_PLAYER1_MAIL=pl1@aaaaamail.com
DJANGO_PLAYER1_PASSWORD=pass1@PASS

# DJANGO_PLAYER2
DJANGO_PLAYER2_USER=playertest2
DJANGO_PLAYER2_MAIL=pl2@aaaaamail.com
DJANGO_PLAYER2_PASSWORD=pass2*PASS

# TOURNAMENT_TIMELIMIT
CREATE_TOURNAMENT_TIMELIMIT_MIN=60
```

**Comment by hachi868** [comment]
auth_userがないと言われてるあたりmigrationsが怪しそう

1.migrationファイル削除
- /backend/scandamus/game/migrations
- /backend/scandamus/players/migrations

2.migrationファイル作りなおし
/backend/tools/docker-entrypoint.sh
L17〜のmigration処理に1行追加
```
python manage.py makemigrations players game
python manage.py makemigrations
python manage.py migrate
```
(※app名追加)

3.DB削除

----
の後に`docker-compose up --build -d`するとどうなりますか？

**Comment by monksoffunk** [comment]
0からcloneしてみるとどうでしょうか？
ほかのブランチからcheckoutしてるとmigrationファイルの不整合が起こりやすいです

**Comment by monksoffunk** [comment]
@Chanmachan 
#208 にも書きましたが、一時しのぎのコミットで現在はほぼ問題を発生させないようにしています（トーナメントの進行に差し障るので）。問題を起こさせるには下記のコミットの変更を戻して試してみてください。
[e430f24](https://github.com/scandamus/ft_transcendence/pull/208/commits/e430f2481a81f577869858d88d39320cbea94e81)

**Comment by Chanmachan** [comment]
別に新しくクローンしてmigrations消してupしなおしたら立ち上がったっぽいです！
ありがとうございました、コミット遡って確認してみます

**Comment by hachi868** [comment]
待合室が設置されて解決したはず
