### ISSUE TITLE
friendページでのFailed to fetch friends

### ISSUE THREAD

**Issue by hachi868** [scandamus/ft_transcendence#97]
https://github.com/scandamus/ft_transcendence/pull/93#issuecomment-2173001491
```
console でこんなエラーが出ることがありましたが、その後は問題なく動作していました


Friends.js:101 
updateFriendList in

api/friends/friends/:1 
       Failed to load resource: the server responded with a status of 403 (Forbidden)

friendsApi.js:21 
Error fetching friends: Error: Failed to fetch friends
    at fetchFriends (friendsApi.js:15:19)
    at async Friends.updateFriendsList (Friends.js:103:29)

Friends.js:123 
Failed to update friends list:  
TypeError: Cannot read properties of undefined (reading 'forEach')
    at Friends.updateFriendsList (Friends.js:107:21)
    
再発したらbackend側のログもほしいです！
```

**Comment by hachi868** [comment]
https://github.com/scandamus/ft_transcendence/issues/145
